### PR TITLE
Switch to spec-prod action and publish to /TR automatically

### PR DESCRIPTION
**Pull request by tidoust**
Publication to gh-pages branch used Travis CI. The recommended way is now to use GitHub jobs with the spec-prod action:
https://github.com/w3c/spec-prod

This action also takes care of keeping /TR in sync with the gh-pages branch, as resolved by the WG:
https://github.com/w3c/media-wg/issues/27

Note publication requires a publication token, which I created and added as a secret in the repo settings, as needed:
https://github.com/w3c/spec-prod/blob/main/docs/options.md#w3c_echidna_token

### CODE REVIEW

**Comment by tidoust** [comment]
Note spec-prod also validates the markup of the spec (and links in theory, but this has been temporarily disabled due to bugs).

**Comment by beaufortfrancois** [comment]
I'm not familiar enough with this to give you a proper review sadly. Do you know someone else?

**Review by beaufortfrancois — COMMENTED** [review]
LGTM

**Comment by tidoust** [comment]
There aren't many things that can be done to validate this on top of giving it a try...

Various repos have the same deploy code, for instance:
- https://github.com/w3c/openscreenprotocol/blob/master/.github/workflows/pr-push.yml
- https://github.com/w3c/webappsec-upgrade-insecure-requests/blob/42022beb0b1757980054e40441fd110b06718866/.github/workflows/build-validate-publish.yml
- https://github.com/w3c/gamepad/blob/451286d0236a61f84cf0ef329f664e9ff1f0de6a/.github/workflows/pr-push.yml
- https://github.com/w3c/image-resource/blob/b8839bc5e10c597b9c68b7d15f3a94a96b616196/.github/workflows/pr-push.yml
- https://github.com/w3c/webrtc-insertable-streams/blob/main/.github/workflows/auto-publish.yml
- https://github.com/w3c/manifest/blob/gh-pages/.github/workflows/action.yml

I'm confident that the publication to `gh-pages` will work without problems, I recently enabled it with the same code for the Open Screen Protocol spec.

For the publication to /TR, the most likely outcome if something's wrong is that W3C's publication system will refuse to publish the update, in which case I would work with @deniak to understand what needs fixing.

**Comment by deniak** [comment]
LGTM as well!

**Comment by tidoust** [comment]
@beaufortfrancois I'll go ahead and merge. If something breaks, I'll look into it...

**Comment by beaufortfrancois** [comment]
No problem. Thanks!

**Comment by deniak** [comment]
The build is actually generating the snapshot for the ED. 
You can add the following config to generate the snapshot so it can be published to /TR.
```
W3C_BUILD_OVERRIDE: |
    shortname: picture-in-picture
    status: WD
```

**Comment by tidoust** [comment]
Ah, that makes sense. I'll add the override for `status`. In our case, `shortname` should not be needed because it already appears in the Bikeshed's metadata. I'll give it a try without.

**Comment by tidoust** [comment]
Automatic publication is now operational \o/

The version in /TR has been updated to match the current ED:
https://www.w3.org/TR/2021/WD-picture-in-picture-20210315/

@beaufortfrancois, I had to commit a few additional changes to fix the automatic publication to:
- Force the status to WD, done in https://github.com/w3c/picture-in-picture/commit/aa3249d1423d4496d55deb2883ab65cfc840e9fe
- Add a "Previous Version" link, done in https://github.com/w3c/picture-in-picture/commit/3377b93d35871a77679f6b55041bc96fe636dddc
- Adjust the spec "level", done in https://github.com/w3c/picture-in-picture/commit/8703d25be145f096501aa5a47e91253374c6f4cc

**Comment by beaufortfrancois** [comment]
Thank you @tidoust!
https://www.w3.org/TR/picture-in-picture/ works great!

**Pull request merged**
